#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     IRseek,         sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Twirler,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    Claw,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers/hitechnic-irseeker-v2.h"
int position = 0; //Might have worked if this was within the If statements and had a if(_dir==1){int position =1 } and so on

void initializeRobot()

{
	return;
}

task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.

	//save IR state here
	//determine what position the beacon is at
	int _dir =HTIRS2readACDir(IRseek);
	//To do test values for range
	if (_dir == 1)
	{
		position =1;
	}
	else if(_dir == 2)
	{
		position =2;
	}
	else if(_dir == 3)
	{
		position =3;
	}
	else if(_dir == 4)
	{
		position =4;
	}
	else if(_dir == 5)
	{
		position =5;
	}else if(_dir == 0)
	{
		position =0;
	}

	if (position ==1)
	{
		if ((_dir)!=1)
		{
			motor[Right]=75;
			motor[Left]=75;
		}
		else{
			motor[Right]=0;
		motor[Left]=0;
		wait1Msec(500);

		motor[Arm]=75;
		wait10Msec(150);

		motor[Right]=75;
		motor[Left]=-75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(50);

		servo[Claw]=150;

		motor[Right]=-75;
		motor[Left]=-75;
		wait10Msec(150);

		motor[Right]=75;
		motor[Left]=-75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(200);

		motor[Right]=-75;
		motor[Left]=75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(50);

		motor[Right]=-75;
		motor[Left]=75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(150);

	}
	if (position ==2)
	{
			if ((_dir)!=1)
		{
			motor[Right]=75;
			motor[Left]=75;
		}
				motor[Right]=0;
		motor[Left]=0;
		wait1Msec(500);

		motor[Arm]=75;
		wait10Msec(150);

		motor[Right]=75;
		motor[Left]=-75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(50);

		servo[Claw]=150;

		motor[Right]=-75;
		motor[Left]=-75;
		wait10Msec(150);

		motor[Right]=75;
		motor[Left]=-75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(250);

		motor[Right]=-75;
		motor[Left]=75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(50);

		motor[Right]=-75;
		motor[Left]=75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(150);
	}
	if (position ==3)
	{
			if ((_dir)!=1)
		{
			motor[Right]=75;
			motor[Left]=75;
		}
				motor[Right]=0;
		motor[Left]=0;
		wait1Msec(500);

		motor[Arm]=75;
		wait10Msec(150);

		motor[Right]=75;
		motor[Left]=-75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(50);

		servo[Claw]=150;

		motor[Right]=-75;
		motor[Left]=-75;
		wait10Msec(150);

		motor[Right]=75;
		motor[Left]=-75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(300);

		motor[Right]=-75;
		motor[Left]=75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(50);

		motor[Right]=-75;
		motor[Left]=75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(150);
	}
	if (position ==4)
	{
			if ((_dir)!=1)
		{
			motor[Right]=75;
			motor[Left]=75;
		}
				motor[Right]=0;
		motor[Left]=0;
		wait1Msec(500);

		motor[Arm]=75;
		wait10Msec(150);

		motor[Right]=75;
		motor[Left]=-75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(50);

		servo[Claw]=150;

		motor[Right]=-75;
		motor[Left]=-75;
		wait10Msec(150);

		motor[Right]=75;
		motor[Left]=-75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(350);

		motor[Right]=-75;
		motor[Left]=75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(50);

		motor[Right]=-75;
		motor[Left]=75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(150);
	}
	if (position ==5)
	{

			if ((_dir)!=1)
		{
			motor[Right]=75;
			motor[Left]=75;
		}

				motor[Right]=0;
		motor[Left]=0;
		wait1Msec(500);

		motor[Arm]=75;
		wait10Msec(150);

		motor[Right]=75;
		motor[Left]=-75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(50);

		servo[Claw]=150;

		motor[Right]=-75;
		motor[Left]=-75;
		wait10Msec(150);

		motor[Right]=75;
		motor[Left]=-75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(400);

		motor[Right]=-75;
		motor[Left]=75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(50);

		motor[Right]=-75;
		motor[Left]=75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(150);
	}
	if (position ==0)
	{
		motor[Right]=0;
		motor[Left]=0;
		wait1Msec(500);

		motor[Arm]=75;
		wait10Msec(150);

		motor[Right]=75;
		motor[Left]=-75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(50);

		servo[Claw]=150;

		motor[Right]=-75;
		motor[Left]=-75;
		wait10Msec(150);

		motor[Right]=75;
		motor[Left]=-75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(200);

		motor[Right]=-75;
		motor[Left]=75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(50);

		motor[Right]=-75;
		motor[Left]=75;
		wait10Msec(100);

		motor[Right]=75;
		motor[Left]=75;
		wait10Msec(150);
	}
	}

}
