#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     HTSPB,          sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     twirler,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    Claw,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "HTSPB-driver.h"
void initializeRobot()
{
	return;
}
float target = 819;// this  is for the PID of the center collum

float integral = 0;

float P = 7.0;
float I = 0.0;

int useless = 0;
float change, change2;
int target2=45;
int serchange,serchange2;
int serchange3,serchange4;
int target3=250;


//[type] identifier(arguments) {
int deadband(int input, int dx)
{
	if (abs(input)<dx)
	{
		input=0;
	}
	return input;
}
//Deadband function that controls the joystick near the middle


task main()
{
	initializeRobot();
  waitForStart();
	while(true)
		{


			int x=joystick.joy1_y2;
			int y=-joystick.joy1_x1; //If it doesn't work replace the 2 with 1 and 1 with 2

			int leftOut = y+x;
			int rightOut = y-x;//If it doesn't work replace the + with - and the - with +
			motor[LeftDrive] = leftOut;
			motor[RightDrive] = rightOut;


		int  current = HTSPBreadADC(HTSPB, 2, 10);
		nxtDisplayTextLine(2, "A0: %f", current);// read integers for superprototype Board

		float joystickVal = joystick.joy2_y1 / 400.0;// reads joystick values and minizes the int recieved
		if(abs(joystick.joy2_y1) > 10)
			target += joystickVal;// changes the setpoint designed to move the arm with the Y axis of joystick


		if (target >857)// upper limit loop to avoid breaking axels
		{
			change = target-857;
			target=target - change;
		}
		if(target < 819)// lower limit loop to avoid breaking axels
		{
			change2=target - 819;
			target = target - change2;
		}
		float error = target-current;
		integral += error;
		if(integral > 1500)
			integral= integral - 700;
		motor[arm]= -(P*error + I * integral);// PID equations


			//int armInput=joystick.joy2_y2;
			//if(armInput < 0) {
			//	armInput/=4;
			//}
			//motor[Arm]=armInput;
			//motor[twirler]=joystick.joy2_y1;
			if(joy2Btn(6))
					{
					servo[Claw]=0;
				}
			else if(joy2Btn(8))
				{
					servo[Claw]=90;
				}
			else
				{
					servo[Claw]=150;
			}
	}
}
